// Generated by gencpp from file swarm_msgs/Square.msg
// DO NOT EDIT!


#ifndef SWARM_MSGS_MESSAGE_SQUARE_H
#define SWARM_MSGS_MESSAGE_SQUARE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace swarm_msgs
{
template <class ContainerAllocator>
struct Square_
{
  typedef Square_<ContainerAllocator> Type;

  Square_()
    : pheromones()  {
      pheromones.assign(0);
  }
  Square_(const ContainerAllocator& _alloc)
    : pheromones()  {
  (void)_alloc;
      pheromones.assign(0);
  }



   typedef boost::array<int8_t, 5>  _pheromones_type;
  _pheromones_type pheromones;





  typedef boost::shared_ptr< ::swarm_msgs::Square_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::swarm_msgs::Square_<ContainerAllocator> const> ConstPtr;

}; // struct Square_

typedef ::swarm_msgs::Square_<std::allocator<void> > Square;

typedef boost::shared_ptr< ::swarm_msgs::Square > SquarePtr;
typedef boost::shared_ptr< ::swarm_msgs::Square const> SquareConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::swarm_msgs::Square_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::swarm_msgs::Square_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::swarm_msgs::Square_<ContainerAllocator1> & lhs, const ::swarm_msgs::Square_<ContainerAllocator2> & rhs)
{
  return lhs.pheromones == rhs.pheromones;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::swarm_msgs::Square_<ContainerAllocator1> & lhs, const ::swarm_msgs::Square_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace swarm_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::swarm_msgs::Square_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swarm_msgs::Square_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_msgs::Square_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm_msgs::Square_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_msgs::Square_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm_msgs::Square_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::swarm_msgs::Square_<ContainerAllocator> >
{
  static const char* value()
  {
    return "98b485e50aa2d6a27ada82a8008715c5";
  }

  static const char* value(const ::swarm_msgs::Square_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x98b485e50aa2d6a2ULL;
  static const uint64_t static_value2 = 0x7ada82a8008715c5ULL;
};

template<class ContainerAllocator>
struct DataType< ::swarm_msgs::Square_<ContainerAllocator> >
{
  static const char* value()
  {
    return "swarm_msgs/Square";
  }

  static const char* value(const ::swarm_msgs::Square_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::swarm_msgs::Square_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8[5] pheromones\n"
;
  }

  static const char* value(const ::swarm_msgs::Square_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::swarm_msgs::Square_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pheromones);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Square_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::swarm_msgs::Square_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::swarm_msgs::Square_<ContainerAllocator>& v)
  {
    s << indent << "pheromones[]" << std::endl;
    for (size_t i = 0; i < v.pheromones.size(); ++i)
    {
      s << indent << "  pheromones[" << i << "]: ";
      Printer<int8_t>::stream(s, indent + "  ", v.pheromones[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SWARM_MSGS_MESSAGE_SQUARE_H
