// Generated by gencpp from file swarm/grid.msg
// DO NOT EDIT!


#ifndef SWARM_MESSAGE_GRID_H
#define SWARM_MESSAGE_GRID_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <swarm/square.h>

namespace swarm
{
template <class ContainerAllocator>
struct grid_
{
  typedef grid_<ContainerAllocator> Type;

  grid_()
    : box()  {
    }
  grid_(const ContainerAllocator& _alloc)
    : box(_alloc)  {
  (void)_alloc;
    }



   typedef  ::swarm::square_<ContainerAllocator>  _box_type;
  _box_type box;





  typedef boost::shared_ptr< ::swarm::grid_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::swarm::grid_<ContainerAllocator> const> ConstPtr;

}; // struct grid_

typedef ::swarm::grid_<std::allocator<void> > grid;

typedef boost::shared_ptr< ::swarm::grid > gridPtr;
typedef boost::shared_ptr< ::swarm::grid const> gridConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::swarm::grid_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::swarm::grid_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::swarm::grid_<ContainerAllocator1> & lhs, const ::swarm::grid_<ContainerAllocator2> & rhs)
{
  return lhs.box == rhs.box;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::swarm::grid_<ContainerAllocator1> & lhs, const ::swarm::grid_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace swarm

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::swarm::grid_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::swarm::grid_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm::grid_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::swarm::grid_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm::grid_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::swarm::grid_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::swarm::grid_<ContainerAllocator> >
{
  static const char* value()
  {
    return "32a280d72cb6e8c663e8b4d302b71970";
  }

  static const char* value(const ::swarm::grid_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x32a280d72cb6e8c6ULL;
  static const uint64_t static_value2 = 0x63e8b4d302b71970ULL;
};

template<class ContainerAllocator>
struct DataType< ::swarm::grid_<ContainerAllocator> >
{
  static const char* value()
  {
    return "swarm/grid";
  }

  static const char* value(const ::swarm::grid_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::swarm::grid_<ContainerAllocator> >
{
  static const char* value()
  {
    return "square box\n"
"================================================================================\n"
"MSG: swarm/square\n"
"char[5] pheromones\n"
;
  }

  static const char* value(const ::swarm::grid_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::swarm::grid_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.box);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct grid_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::swarm::grid_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::swarm::grid_<ContainerAllocator>& v)
  {
    s << indent << "box: ";
    s << std::endl;
    Printer< ::swarm::square_<ContainerAllocator> >::stream(s, indent + "  ", v.box);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SWARM_MESSAGE_GRID_H
